// Code generated by `charly task cue-gen` (internal/schemagen); DO NOT EDIT.
//
// The HEAD schema CalVer + the oldest migratable floor, derived from
// schema/version.cue. kit.LatestSchemaVersion()/SchemaFloor() parse
// these; never hand-edit — regenerate with `charly task cue-gen`.

package spec

// SchemaVersion is the HEAD schema CalVer (schema/version.cue #SchemaVersion).
const SchemaVersion = "2026.261.1747"

// SchemaFloor is the oldest schema version `charly migrate` can migrate FROM
// (schema/version.cue #SchemaFloor).
const SchemaFloor = "2026.174.1100"
