// Code generated by `task cue:gen` (internal/schemagen); DO NOT EDIT.
//
// The single-source vocabulary, derived from schema/*.cue. These are
// the SAME word lists the runtime validates against — never hand-maintain a
// parallel copy; regenerate with `task cue:gen`.

package spec

// KindWords is the reserved kind keywords (the #Node disjunction discriminators).
var KindWords = []string{}

// ResourceKinds is the DEPLOYABLE subset of the kind keywords — the kinds whose #Node arm nests a sub-ENTITY (resource) child (#ResourceKind).
var ResourceKinds = []string{
	"pod",
	"vm",
	"kubernetes",
	"local",
	"android",
	"group",
}

// DocDirectives is the reserved document directives (#NodeDoc top-level keys).
var DocDirectives = []string{
	"cache",
	"compiled_plugins",
	"context_ignore_baseline",
	"defaults",
	"discover",
	"import",
	"ledger",
	"ovmf_distro_aliases",
	"ovmf_paths",
	"providers",
	"provides",
	"repo",
	"system",
	"version",
}

// DistroIDs is the CLOSED guest-distro id vocabulary, derived from #Distros' own keys (schema/distro_vocab.cue).
var DistroIDs = []string{
	"almalinux",
	"alpine",
	"arch",
	"archarm",
	"cachyos",
	"centos",
	"debian",
	"endeavouros",
	"fedora",
	"manjaro",
	"omarchy",
	"rhel",
	"rocky",
	"ubuntu",
}

// DistroFormats is each distro id's native package format (#Distros[id].format). The SINGLE table — hostenv.FormatForDistroID reads it; there is no hand-written Go copy.
var DistroFormats = map[string]string{
	"almalinux":   "rpm",
	"alpine":      "apk",
	"arch":        "pac",
	"archarm":     "pac",
	"cachyos":     "pac",
	"centos":      "rpm",
	"debian":      "deb",
	"endeavouros": "pac",
	"fedora":      "rpm",
	"manjaro":     "pac",
	"omarchy":     "pac",
	"rhel":        "rpm",
	"rocky":       "rpm",
	"ubuntu":      "deb",
}

// DistroSSHUnits is each distro id's OpenSSH service name (#Distros[id].ssh_unit) — `ssh` on Debian-family, `sshd` elsewhere. Replaces a hardcoded Go switch.
var DistroSSHUnits = map[string]string{
	"almalinux":   "sshd",
	"alpine":      "sshd",
	"arch":        "sshd",
	"archarm":     "sshd",
	"cachyos":     "sshd",
	"centos":      "sshd",
	"debian":      "ssh",
	"endeavouros": "sshd",
	"fedora":      "sshd",
	"manjaro":     "sshd",
	"omarchy":     "sshd",
	"rhel":        "sshd",
	"rocky":       "sshd",
	"ubuntu":      "ssh",
}

// DistroInits is each distro id's guest init system (#Distros[id].init) — systemd or openrc. Replaces `if distro == "alpine"` branches.
var DistroInits = map[string]string{
	"almalinux":   "systemd",
	"alpine":      "openrc",
	"arch":        "systemd",
	"archarm":     "systemd",
	"cachyos":     "systemd",
	"centos":      "systemd",
	"debian":      "systemd",
	"endeavouros": "systemd",
	"fedora":      "systemd",
	"manjaro":     "systemd",
	"omarchy":     "systemd",
	"rhel":        "systemd",
	"rocky":       "systemd",
	"ubuntu":      "systemd",
}

// DistroOvmfFamilies is each distro id's OVMF firmware family (#Distros[id].ovmf_family), for the ids that declare one. Replaces the hand-maintained ovmf_distro_aliases: map that was kept in two byte-identical copies. An id with no entry keeps the all-families fallback.
var DistroOvmfFamilies = map[string]string{
	"almalinux":   "fedora",
	"arch":        "arch",
	"cachyos":     "arch",
	"centos":      "fedora",
	"debian":      "debian",
	"endeavouros": "arch",
	"fedora":      "fedora",
	"manjaro":     "arch",
	"omarchy":     "arch",
	"rhel":        "fedora",
	"rocky":       "fedora",
	"ubuntu":      "debian",
}

// StepKeywords is the plan-step intent keywords (#Step arms minus #Op fields).
var StepKeywords = []string{
	"agent-check",
	"agent-run",
	"check",
	"include",
	"run",
}

// ContextWords is the plan-step execution contexts (#Context).
var ContextWords = []string{
	"build",
	"deploy",
	"runtime",
}

// OpFields is every #Op verb/modifier field name (the flat Op vocabulary).
var OpFields = []string{
	"build",
	"cache",
	"caps",
	"command",
	"comment",
	"content",
	"context",
	"copy",
	"depends_on",
	"description",
	"download",
	"env",
	"eventually",
	"exclude_distro",
	"exit_status",
	"extract",
	"extract_include",
	"id",
	"intent_do",
	"link",
	"mkdir",
	"mode",
	"origin",
	"plugin",
	"plugin_input",
	"retry_interval",
	"run_as",
	"setcap",
	"skip",
	"stderr",
	"stdout",
	"strip_components",
	"tag",
	"target",
	"timeout",
	"to",
	"uninstall",
	"unless_exists",
	"venue",
	"write",
}

// OpVerbs is the verb DISCRIMINATOR vocabulary (#OpVerb) — the exactly-one-set verb subset of #Op fields (Op.Kind() + the VerbCatalog dispatch table gate against it).
var OpVerbs = []string{
	"mkdir",
	"copy",
	"write",
	"link",
	"download",
	"setcap",
	"build",
	"plugin",
}

// AuthoringVerbs is the AUTHORABLE #Op field vocabulary (#Op fields minus the never-authored origin/venue/intent_do/plugin/plugin_input/command).
var AuthoringVerbs = []string{
	"build",
	"cache",
	"caps",
	"comment",
	"content",
	"context",
	"copy",
	"depends_on",
	"description",
	"download",
	"env",
	"eventually",
	"exclude_distro",
	"exit_status",
	"extract",
	"extract_include",
	"id",
	"link",
	"mkdir",
	"mode",
	"retry_interval",
	"run_as",
	"setcap",
	"skip",
	"stderr",
	"stdout",
	"strip_components",
	"tag",
	"target",
	"timeout",
	"to",
	"uninstall",
	"unless_exists",
	"write",
}

// KindValueDefs is the word→#<Kind>Value CUE-def map the host uses to closedness-gate a substrate/candy node's authored VALUE (validateKindValueCUE). DERIVED from the #<X>Value defs themselves (every one except the shared #DeployValue disjunct), so a new value-gated kind needs no hand-maintained map.
var KindValueDefs = map[string]string{
	"android":    "#AndroidValue",
	"candy":      "#CandyValue",
	"kubernetes": "#KubernetesValue",
	"local":      "#LocalValue",
	"pod":        "#PodValue",
	"vm":         "#VmValue",
}
