// Code generated by sdk/internal/wiregen from protocol/schema/*.cue. DO NOT EDIT.
// CUE is the authoritative source for this transport contract.

// The Charly plugin gRPC contract. One Provider service mirrors the unified
// provider interface; typed protobuf messages carry transport, streaming,
// and handshake control while CUE-generated JSON payloads carry domain data.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginMeta_Describe_FullMethodName = "/charlyplugin.PluginMeta/Describe"
)

// PluginMetaClient is the client API for PluginMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginMetaClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
}

type pluginMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginMetaClient(cc grpc.ClientConnInterface) PluginMetaClient {
	return &pluginMetaClient{cc}
}

func (c *pluginMetaClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, PluginMeta_Describe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginMetaServer is the server API for PluginMeta service.
// All implementations must embed UnimplementedPluginMetaServer
// for forward compatibility
type PluginMetaServer interface {
	Describe(context.Context, *Empty) (*Capabilities, error)
	mustEmbedUnimplementedPluginMetaServer()
}

// UnimplementedPluginMetaServer must be embedded to have forward compatible implementations.
type UnimplementedPluginMetaServer struct {
}

func (UnimplementedPluginMetaServer) Describe(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginMetaServer) mustEmbedUnimplementedPluginMetaServer() {}

// UnsafePluginMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginMetaServer will
// result in compilation errors.
type UnsafePluginMetaServer interface {
	mustEmbedUnimplementedPluginMetaServer()
}

func RegisterPluginMetaServer(s grpc.ServiceRegistrar, srv PluginMetaServer) {
	s.RegisterService(&PluginMeta_ServiceDesc, srv)
}

func _PluginMeta_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMetaServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMeta_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMetaServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginMeta_ServiceDesc is the grpc.ServiceDesc for PluginMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.PluginMeta",
	HandlerType: (*PluginMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginMeta_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Provider_Invoke_FullMethodName       = "/charlyplugin.Provider/Invoke"
	Provider_InvokeStream_FullMethodName = "/charlyplugin.Provider/InvokeStream"
	Provider_Channel_FullMethodName      = "/charlyplugin.Provider/Channel"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderClient interface {
	// single-shot (the common path)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	// streaming (record/logcat/execute)
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error)
	// generic bidirectional provider/process stream with explicit ordering, acknowledgements, cancellation, and resynchronization
	Channel(ctx context.Context, opts ...grpc.CallOption) (Provider_ChannelClient, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, Provider_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[0], Provider_InvokeStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &providerInvokeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Provider_InvokeStreamClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type providerInvokeStreamClient struct {
	grpc.ClientStream
}

func (x *providerInvokeStreamClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerClient) Channel(ctx context.Context, opts ...grpc.CallOption) (Provider_ChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[1], Provider_Channel_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &providerChannelClient{stream}
	return x, nil
}

type Provider_ChannelClient interface {
	Send(*ChannelFrame) error
	Recv() (*ChannelFrame, error)
	grpc.ClientStream
}

type providerChannelClient struct {
	grpc.ClientStream
}

func (x *providerChannelClient) Send(m *ChannelFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *providerChannelClient) Recv() (*ChannelFrame, error) {
	m := new(ChannelFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility
type ProviderServer interface {
	// single-shot (the common path)
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
	// streaming (record/logcat/execute)
	InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error
	// generic bidirectional provider/process stream with explicit ordering, acknowledgements, cancellation, and resynchronization
	Channel(Provider_ChannelServer) error
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (UnimplementedProviderServer) Invoke(context.Context, *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedProviderServer) InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedProviderServer) Channel(Provider_ChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServer).InvokeStream(m, &providerInvokeStreamServer{stream})
}

type Provider_InvokeStreamServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type providerInvokeStreamServer struct {
	grpc.ServerStream
}

func (x *providerInvokeStreamServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Provider_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).Channel(&providerChannelServer{stream})
}

type Provider_ChannelServer interface {
	Send(*ChannelFrame) error
	Recv() (*ChannelFrame, error)
	grpc.ServerStream
}

type providerChannelServer struct {
	grpc.ServerStream
}

func (x *providerChannelServer) Send(m *ChannelFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *providerChannelServer) Recv() (*ChannelFrame, error) {
	m := new(ChannelFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Provider_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _Provider_InvokeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Channel",
			Handler:       _Provider_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	ExecutorService_Venue_FullMethodName            = "/charlyplugin.ExecutorService/Venue"
	ExecutorService_RunSystem_FullMethodName        = "/charlyplugin.ExecutorService/RunSystem"
	ExecutorService_RunUser_FullMethodName          = "/charlyplugin.ExecutorService/RunUser"
	ExecutorService_PutFile_FullMethodName          = "/charlyplugin.ExecutorService/PutFile"
	ExecutorService_RunCapture_FullMethodName       = "/charlyplugin.ExecutorService/RunCapture"
	ExecutorService_RunInteractive_FullMethodName   = "/charlyplugin.ExecutorService/RunInteractive"
	ExecutorService_RunStream_FullMethodName        = "/charlyplugin.ExecutorService/RunStream"
	ExecutorService_GetFile_FullMethodName          = "/charlyplugin.ExecutorService/GetFile"
	ExecutorService_RunHostStep_FullMethodName      = "/charlyplugin.ExecutorService/RunHostStep"
	ExecutorService_InvokeProvider_FullMethodName   = "/charlyplugin.ExecutorService/InvokeProvider"
	ExecutorService_HostBuild_FullMethodName        = "/charlyplugin.ExecutorService/HostBuild"
	ExecutorService_DescribeProvider_FullMethodName = "/charlyplugin.ExecutorService/DescribeProvider"
)

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorServiceClient interface {
	Venue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VenueReply, error)
	RunSystem(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	RunUser(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	// place file content on the venue (binary-safe; owner_root → root:root via sudo)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileReply, error)
	// capture stdout/stderr/exit (no root escalation — callers add sudo)
	RunCapture(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CaptureReply, error)
	// F12: run script on the venue wired to the operator's LIVE TTY (the host reverse-server runs IN the charly process, so it inherits os.Stdin/os.Stdout/os.Stderr = the operator's terminal — stdio NEVER crosses the wire, only script→exit; the child podman exec -it / ssh -t owns the PTY + resize + Ctrl-C). Blocks until the session ends; UNARY (host holds the TTY — the hostBuildCli doctrine). Consumers: charly shell (-it), charly cmd (-i)
	RunInteractive(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*LiveReply, error)
	// F12: run script on the venue streaming stdout/stderr LIVE to the operator (inherited os.Stdout/os.Stderr; no stdin). Blocks until exit. UNARY (host holds the terminal). Consumer: charly logs --follow
	RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*LiveReply, error)
	// read a venue file (e.g. a record/screenshot artifact pulled back to the host)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileReply, error)
	// run a HOST-ENGINE step (Builder/LocalPkgInstall/SystemPackages/act-OpStep/ExternalPlugin) on the host engine + apply onto the venue
	RunHostStep(ctx context.Context, in *HostStepRequest, opts ...grpc.CallOption) (*HostStepReply, error)
	// F10 plugin↔plugin: the host resolves another provider by (class,word) + Invokes it on the calling plugin's behalf (threading the SAME venue executor) — the generalization of the RunHostStep ExternalPlugin arm to ANY class/op
	InvokeProvider(ctx context.Context, in *InvokeProviderRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	// F10 host-build: the calling plugin requests a HOST-side build (the build engine stays in core) — the host runs the registered host-builder for `kind` and returns its result
	HostBuild(ctx context.Context, in *HostBuildRequest, opts ...grpc.CallOption) (*HostBuildReply, error)
	// K5-A item 2: the host resolves another provider by (class,word) and returns its CACHED capability metadata (today: StepContract) — no Invoke, no live Describe round-trip. The metadata twin of InvokeProvider (dispatch) and HostBuild (host-side build).
	DescribeProvider(ctx context.Context, in *DescribeProviderRequest, opts ...grpc.CallOption) (*DescribeProviderReply, error)
}

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) Venue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VenueReply, error) {
	out := new(VenueReply)
	err := c.cc.Invoke(ctx, ExecutorService_Venue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunSystem(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunUser(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileReply, error) {
	out := new(PutFileReply)
	err := c.cc.Invoke(ctx, ExecutorService_PutFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunCapture(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CaptureReply, error) {
	out := new(CaptureReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunCapture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunInteractive(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*LiveReply, error) {
	out := new(LiveReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunInteractive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*LiveReply, error) {
	out := new(LiveReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunStream_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileReply, error) {
	out := new(GetFileReply)
	err := c.cc.Invoke(ctx, ExecutorService_GetFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunHostStep(ctx context.Context, in *HostStepRequest, opts ...grpc.CallOption) (*HostStepReply, error) {
	out := new(HostStepReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunHostStep_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) InvokeProvider(ctx context.Context, in *InvokeProviderRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, ExecutorService_InvokeProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) HostBuild(ctx context.Context, in *HostBuildRequest, opts ...grpc.CallOption) (*HostBuildReply, error) {
	out := new(HostBuildReply)
	err := c.cc.Invoke(ctx, ExecutorService_HostBuild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) DescribeProvider(ctx context.Context, in *DescribeProviderRequest, opts ...grpc.CallOption) (*DescribeProviderReply, error) {
	out := new(DescribeProviderReply)
	err := c.cc.Invoke(ctx, ExecutorService_DescribeProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
// All implementations must embed UnimplementedExecutorServiceServer
// for forward compatibility
type ExecutorServiceServer interface {
	Venue(context.Context, *Empty) (*VenueReply, error)
	RunSystem(context.Context, *RunRequest) (*RunReply, error)
	RunUser(context.Context, *RunRequest) (*RunReply, error)
	// place file content on the venue (binary-safe; owner_root → root:root via sudo)
	PutFile(context.Context, *PutFileRequest) (*PutFileReply, error)
	// capture stdout/stderr/exit (no root escalation — callers add sudo)
	RunCapture(context.Context, *RunRequest) (*CaptureReply, error)
	// F12: run script on the venue wired to the operator's LIVE TTY (the host reverse-server runs IN the charly process, so it inherits os.Stdin/os.Stdout/os.Stderr = the operator's terminal — stdio NEVER crosses the wire, only script→exit; the child podman exec -it / ssh -t owns the PTY + resize + Ctrl-C). Blocks until the session ends; UNARY (host holds the TTY — the hostBuildCli doctrine). Consumers: charly shell (-it), charly cmd (-i)
	RunInteractive(context.Context, *RunRequest) (*LiveReply, error)
	// F12: run script on the venue streaming stdout/stderr LIVE to the operator (inherited os.Stdout/os.Stderr; no stdin). Blocks until exit. UNARY (host holds the terminal). Consumer: charly logs --follow
	RunStream(context.Context, *RunRequest) (*LiveReply, error)
	// read a venue file (e.g. a record/screenshot artifact pulled back to the host)
	GetFile(context.Context, *GetFileRequest) (*GetFileReply, error)
	// run a HOST-ENGINE step (Builder/LocalPkgInstall/SystemPackages/act-OpStep/ExternalPlugin) on the host engine + apply onto the venue
	RunHostStep(context.Context, *HostStepRequest) (*HostStepReply, error)
	// F10 plugin↔plugin: the host resolves another provider by (class,word) + Invokes it on the calling plugin's behalf (threading the SAME venue executor) — the generalization of the RunHostStep ExternalPlugin arm to ANY class/op
	InvokeProvider(context.Context, *InvokeProviderRequest) (*InvokeReply, error)
	// F10 host-build: the calling plugin requests a HOST-side build (the build engine stays in core) — the host runs the registered host-builder for `kind` and returns its result
	HostBuild(context.Context, *HostBuildRequest) (*HostBuildReply, error)
	// K5-A item 2: the host resolves another provider by (class,word) and returns its CACHED capability metadata (today: StepContract) — no Invoke, no live Describe round-trip. The metadata twin of InvokeProvider (dispatch) and HostBuild (host-side build).
	DescribeProvider(context.Context, *DescribeProviderRequest) (*DescribeProviderReply, error)
	mustEmbedUnimplementedExecutorServiceServer()
}

// UnimplementedExecutorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExecutorServiceServer struct {
}

func (UnimplementedExecutorServiceServer) Venue(context.Context, *Empty) (*VenueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Venue not implemented")
}
func (UnimplementedExecutorServiceServer) RunSystem(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSystem not implemented")
}
func (UnimplementedExecutorServiceServer) RunUser(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunUser not implemented")
}
func (UnimplementedExecutorServiceServer) PutFile(context.Context, *PutFileRequest) (*PutFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedExecutorServiceServer) RunCapture(context.Context, *RunRequest) (*CaptureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCapture not implemented")
}
func (UnimplementedExecutorServiceServer) RunInteractive(context.Context, *RunRequest) (*LiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunInteractive not implemented")
}
func (UnimplementedExecutorServiceServer) RunStream(context.Context, *RunRequest) (*LiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStream not implemented")
}
func (UnimplementedExecutorServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedExecutorServiceServer) RunHostStep(context.Context, *HostStepRequest) (*HostStepReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunHostStep not implemented")
}
func (UnimplementedExecutorServiceServer) InvokeProvider(context.Context, *InvokeProviderRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeProvider not implemented")
}
func (UnimplementedExecutorServiceServer) HostBuild(context.Context, *HostBuildRequest) (*HostBuildReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostBuild not implemented")
}
func (UnimplementedExecutorServiceServer) DescribeProvider(context.Context, *DescribeProviderRequest) (*DescribeProviderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeProvider not implemented")
}
func (UnimplementedExecutorServiceServer) mustEmbedUnimplementedExecutorServiceServer() {}

// UnsafeExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServiceServer will
// result in compilation errors.
type UnsafeExecutorServiceServer interface {
	mustEmbedUnimplementedExecutorServiceServer()
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	s.RegisterService(&ExecutorService_ServiceDesc, srv)
}

func _ExecutorService_Venue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Venue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_Venue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Venue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunSystem(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunUser(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_PutFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunCapture(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunInteractive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunInteractive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunInteractive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunInteractive(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunStream(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunHostStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunHostStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunHostStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunHostStep(ctx, req.(*HostStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_InvokeProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).InvokeProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_InvokeProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).InvokeProvider(ctx, req.(*InvokeProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_HostBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).HostBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_HostBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).HostBuild(ctx, req.(*HostBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_DescribeProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).DescribeProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_DescribeProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).DescribeProvider(ctx, req.(*DescribeProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutorService_ServiceDesc is the grpc.ServiceDesc for ExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Venue",
			Handler:    _ExecutorService_Venue_Handler,
		},
		{
			MethodName: "RunSystem",
			Handler:    _ExecutorService_RunSystem_Handler,
		},
		{
			MethodName: "RunUser",
			Handler:    _ExecutorService_RunUser_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _ExecutorService_PutFile_Handler,
		},
		{
			MethodName: "RunCapture",
			Handler:    _ExecutorService_RunCapture_Handler,
		},
		{
			MethodName: "RunInteractive",
			Handler:    _ExecutorService_RunInteractive_Handler,
		},
		{
			MethodName: "RunStream",
			Handler:    _ExecutorService_RunStream_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _ExecutorService_GetFile_Handler,
		},
		{
			MethodName: "RunHostStep",
			Handler:    _ExecutorService_RunHostStep_Handler,
		},
		{
			MethodName: "InvokeProvider",
			Handler:    _ExecutorService_InvokeProvider_Handler,
		},
		{
			MethodName: "HostBuild",
			Handler:    _ExecutorService_HostBuild_Handler,
		},
		{
			MethodName: "DescribeProvider",
			Handler:    _ExecutorService_DescribeProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	CheckContextService_HTTPDo_FullMethodName                  = "/charlyplugin.CheckContextService/HTTPDo"
	CheckContextService_AddBackground_FullMethodName           = "/charlyplugin.CheckContextService/AddBackground"
	CheckContextService_ResolveEndpoint_FullMethodName         = "/charlyplugin.CheckContextService/ResolveEndpoint"
	CheckContextService_ResolveGraphicsEndpoint_FullMethodName = "/charlyplugin.CheckContextService/ResolveGraphicsEndpoint"
	CheckContextService_ResolveImageLabel_FullMethodName       = "/charlyplugin.CheckContextService/ResolveImageLabel"
)

// CheckContextServiceClient is the client API for CheckContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckContextServiceClient interface {
	HTTPDo(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoReply, error)
	AddBackground(ctx context.Context, in *AddBackgroundRequest, opts ...grpc.CallOption) (*Empty, error)
	// ResolveEndpoint: resolve the check target's venue (container / VM / ssh / local) and
	// return a host-reachable address for an in-venue TCP port — opening (and host-side
	// tracking, for post-Invoke teardown) any ssh -L forward a VM/ssh venue needs. Class-
	// generic: ANY endpoint check verb (cdp/vnc/spice/…) declares its port and dials the addr.
	ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointReply, error)
	// ResolveGraphicsEndpoint: resolve a VM's <graphics type='<kind>'> listener (kind = "vnc"
	// | "spice") to a dialable endpoint — the host owns the go-libvirt resolution, any
	// qemu+ssh:// tunnel (tracked for post-Invoke teardown), the socket->TCP bridge a TCP-only
	// client needs, and the credential-store password. Class-generic: parameterized by kind,
	// shared by the vnc + spice verbs (never a per-verb RPC).
	ResolveGraphicsEndpoint(ctx context.Context, in *ResolveGraphicsEndpointRequest, opts ...grpc.CallOption) (*ResolveGraphicsEndpointReply, error)
	// ResolveImageLabel: read one OCI label value off the deployment-under-test's image — the
	// host owns the podman engine + container→image resolution the out-of-process plugin cannot
	// reach. Class-generic (parameterized by label name): the mcp verb reads ai.opencharly.mcp_provide;
	// any verb needing a baked label uses it. Empty value (label absent) is a valid reply.
	ResolveImageLabel(ctx context.Context, in *ResolveImageLabelRequest, opts ...grpc.CallOption) (*ResolveImageLabelReply, error)
}

type checkContextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckContextServiceClient(cc grpc.ClientConnInterface) CheckContextServiceClient {
	return &checkContextServiceClient{cc}
}

func (c *checkContextServiceClient) HTTPDo(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoReply, error) {
	out := new(HTTPDoReply)
	err := c.cc.Invoke(ctx, CheckContextService_HTTPDo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkContextServiceClient) AddBackground(ctx context.Context, in *AddBackgroundRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CheckContextService_AddBackground_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkContextServiceClient) ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointReply, error) {
	out := new(ResolveEndpointReply)
	err := c.cc.Invoke(ctx, CheckContextService_ResolveEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkContextServiceClient) ResolveGraphicsEndpoint(ctx context.Context, in *ResolveGraphicsEndpointRequest, opts ...grpc.CallOption) (*ResolveGraphicsEndpointReply, error) {
	out := new(ResolveGraphicsEndpointReply)
	err := c.cc.Invoke(ctx, CheckContextService_ResolveGraphicsEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkContextServiceClient) ResolveImageLabel(ctx context.Context, in *ResolveImageLabelRequest, opts ...grpc.CallOption) (*ResolveImageLabelReply, error) {
	out := new(ResolveImageLabelReply)
	err := c.cc.Invoke(ctx, CheckContextService_ResolveImageLabel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckContextServiceServer is the server API for CheckContextService service.
// All implementations must embed UnimplementedCheckContextServiceServer
// for forward compatibility
type CheckContextServiceServer interface {
	HTTPDo(context.Context, *HTTPDoRequest) (*HTTPDoReply, error)
	AddBackground(context.Context, *AddBackgroundRequest) (*Empty, error)
	// ResolveEndpoint: resolve the check target's venue (container / VM / ssh / local) and
	// return a host-reachable address for an in-venue TCP port — opening (and host-side
	// tracking, for post-Invoke teardown) any ssh -L forward a VM/ssh venue needs. Class-
	// generic: ANY endpoint check verb (cdp/vnc/spice/…) declares its port and dials the addr.
	ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointReply, error)
	// ResolveGraphicsEndpoint: resolve a VM's <graphics type='<kind>'> listener (kind = "vnc"
	// | "spice") to a dialable endpoint — the host owns the go-libvirt resolution, any
	// qemu+ssh:// tunnel (tracked for post-Invoke teardown), the socket->TCP bridge a TCP-only
	// client needs, and the credential-store password. Class-generic: parameterized by kind,
	// shared by the vnc + spice verbs (never a per-verb RPC).
	ResolveGraphicsEndpoint(context.Context, *ResolveGraphicsEndpointRequest) (*ResolveGraphicsEndpointReply, error)
	// ResolveImageLabel: read one OCI label value off the deployment-under-test's image — the
	// host owns the podman engine + container→image resolution the out-of-process plugin cannot
	// reach. Class-generic (parameterized by label name): the mcp verb reads ai.opencharly.mcp_provide;
	// any verb needing a baked label uses it. Empty value (label absent) is a valid reply.
	ResolveImageLabel(context.Context, *ResolveImageLabelRequest) (*ResolveImageLabelReply, error)
	mustEmbedUnimplementedCheckContextServiceServer()
}

// UnimplementedCheckContextServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckContextServiceServer struct {
}

func (UnimplementedCheckContextServiceServer) HTTPDo(context.Context, *HTTPDoRequest) (*HTTPDoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HTTPDo not implemented")
}
func (UnimplementedCheckContextServiceServer) AddBackground(context.Context, *AddBackgroundRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackground not implemented")
}
func (UnimplementedCheckContextServiceServer) ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveEndpoint not implemented")
}
func (UnimplementedCheckContextServiceServer) ResolveGraphicsEndpoint(context.Context, *ResolveGraphicsEndpointRequest) (*ResolveGraphicsEndpointReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveGraphicsEndpoint not implemented")
}
func (UnimplementedCheckContextServiceServer) ResolveImageLabel(context.Context, *ResolveImageLabelRequest) (*ResolveImageLabelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveImageLabel not implemented")
}
func (UnimplementedCheckContextServiceServer) mustEmbedUnimplementedCheckContextServiceServer() {}

// UnsafeCheckContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckContextServiceServer will
// result in compilation errors.
type UnsafeCheckContextServiceServer interface {
	mustEmbedUnimplementedCheckContextServiceServer()
}

func RegisterCheckContextServiceServer(s grpc.ServiceRegistrar, srv CheckContextServiceServer) {
	s.RegisterService(&CheckContextService_ServiceDesc, srv)
}

func _CheckContextService_HTTPDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPDoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).HTTPDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_HTTPDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).HTTPDo(ctx, req.(*HTTPDoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckContextService_AddBackground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackgroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).AddBackground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_AddBackground_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).AddBackground(ctx, req.(*AddBackgroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckContextService_ResolveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).ResolveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_ResolveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).ResolveEndpoint(ctx, req.(*ResolveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckContextService_ResolveGraphicsEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveGraphicsEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).ResolveGraphicsEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_ResolveGraphicsEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).ResolveGraphicsEndpoint(ctx, req.(*ResolveGraphicsEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckContextService_ResolveImageLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveImageLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).ResolveImageLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_ResolveImageLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).ResolveImageLabel(ctx, req.(*ResolveImageLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckContextService_ServiceDesc is the grpc.ServiceDesc for CheckContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.CheckContextService",
	HandlerType: (*CheckContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HTTPDo",
			Handler:    _CheckContextService_HTTPDo_Handler,
		},
		{
			MethodName: "AddBackground",
			Handler:    _CheckContextService_AddBackground_Handler,
		},
		{
			MethodName: "ResolveEndpoint",
			Handler:    _CheckContextService_ResolveEndpoint_Handler,
		},
		{
			MethodName: "ResolveGraphicsEndpoint",
			Handler:    _CheckContextService_ResolveGraphicsEndpoint_Handler,
		},
		{
			MethodName: "ResolveImageLabel",
			Handler:    _CheckContextService_ResolveImageLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
