// Code generated by spec/internal/wiregen from protocol/schema/*.cue. DO NOT EDIT.
// CUE is the authoritative source for this transport contract.

// The Charly plugin gRPC contract. One Provider service mirrors the unified
// provider interface; typed protobuf messages carry transport, streaming,
// and handshake control while CUE-generated JSON payloads carry domain data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the plugin's CalVer (CalVer is the version authority)
	Calver string `protobuf:"bytes,1,opt,name=calver,proto3" json:"calver,omitempty"`
	// thin secondary gate; never duplicates CalVer
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// the unit's capabilities + the def validating each input
	Provided []*ProvidedCapability `protobuf:"bytes,3,rep,name=provided,proto3" json:"provided,omitempty"`
	// the unit's package-less, SELF-CONTAINED .cue source text
	SchemaCue     string `protobuf:"bytes,4,opt,name=schema_cue,json=schemaCue,proto3" json:"schema_cue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetCalver() string {
	if x != nil {
		return x.Calver
	}
	return ""
}

func (x *Capabilities) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Capabilities) GetProvided() []*ProvidedCapability {
	if x != nil {
		return x.Provided
	}
	return nil
}

func (x *Capabilities) GetSchemaCue() string {
	if x != nil {
		return x.SchemaCue
	}
	return ""
}

// ProvidedCapability — one served capability plus the CUE def that validates its
// plugin_input. The schema travels with the plugin over Describe (the same channel
// for in-proc builtin and out-of-proc external — zero distinction), so the host
// validates authored plugin_input against `base ++ served` without ever reading a
// candy's schema/ dir. `input_def` is explicit (no Title-case naming convention).
type ProvidedCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "verb" / "kind" / "deploy" / "step" / "builder"
	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// the reserved word, e.g. "externalprobe"
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	// the CUE def for this word's plugin_input, e.g. "#ExternalprobeInput"
	InputDef string `protobuf:"bytes,3,opt,name=input_def,json=inputDef,proto3" json:"input_def,omitempty"`
	// set ONLY for class="step" (F3): the plugin-declared install-step contract
	StepContract *StepContract `protobuf:"bytes,4,opt,name=step_contract,json=stepContract,proto3" json:"step_contract,omitempty"`
	// set ONLY for class="kind" (F5): the kind decodes a STRUCTURAL entity (a spec.Deploy member tree -> uf.Fleet) rather than a FLAT body (-> uf.PluginKinds)
	Structural bool `protobuf:"varint,5,opt,name=structural,proto3" json:"structural,omitempty"`
	// set ONLY for class="deploy" (F6): the substrate brings its OWN host-side venue lifecycle (PrepareVenue/Start/Stop/...) served over the lifecycle Ops; the host registers a wire-backed substrateLifecycle for it
	Lifecycle bool `protobuf:"varint,6,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	// set ONLY for class="deploy" (F6): the substrate declares a host-side PRERESOLVE step (OpPreresolve) the host runs before apply, shipping the opaque result in DeployVenue.Substrate
	Preresolve bool `protobuf:"varint,7,opt,name=preresolve,proto3" json:"preresolve,omitempty"`
	// set ONLY for class="kind" (F7/C8): the kind serves a deep OpValidate check (returns Diagnostics) BEYOND the static CUE input-def gate; the host dispatches OpValidate at load
	Validates bool `protobuf:"varint,8,opt,name=validates,proto3" json:"validates,omitempty"`
	// F9: the plugin lifecycle PHASE (sdk.Phase*; "" => runtime default) — the ordered point at which the kernel loads/invokes the plugin; "bootstrap" runs BEFORE config validation/migration
	Phase string `protobuf:"bytes,9,opt,name=phase,proto3" json:"phase,omitempty"`
	// set ONLY for class="verb": the input field the scalar sugar shorthand targets (`file: /x` -> plugin_input: {<primary>: "/x"}); "" => map input only
	Primary string `protobuf:"bytes,10,opt,name=primary,proto3" json:"primary,omitempty"`
	// set ONLY for class="kind" (P9): a SUBSTRATE kind's DECLARED deploy behaviour traits, the SINGLE plugin-declared source kit.StampDescent stamps onto node.Descent — the consult sites read the traits off node.Descent instead of switching on the substrate kind word
	DeployTraits *DeployTraits `protobuf:"bytes,11,opt,name=deploy_traits,json=deployTraits,proto3" json:"deploy_traits,omitempty"`
	// set ONLY for class="command": the plugin's DECLARED one-level-deep CLI subcommand catalog (name+help). Lets the host build a REAL nested Kong grammar (in place of the opaque `[<args>...]` pass-through holder every command-class capability otherwise gets) and synthesize a dotted "<word>.<name>" CLI-model leaf per entry for `charly __cli-model` / MCP tool generation. Empty (the default) preserves today's flat pass-through behavior byte-for-byte.
	Subcommands []*CLISubcommand `protobuf:"bytes,12,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	// CUE #CLIModel JSON for class=command; lets CLI and MCP reflect plugin-owned leaves without importing plugin code
	CommandModelJson []byte `protobuf:"bytes,13,opt,name=command_model_json,json=commandModelJson,proto3" json:"command_model_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvidedCapability) Reset() {
	*x = ProvidedCapability{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidedCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidedCapability) ProtoMessage() {}

func (x *ProvidedCapability) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidedCapability.ProtoReflect.Descriptor instead.
func (*ProvidedCapability) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ProvidedCapability) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ProvidedCapability) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *ProvidedCapability) GetInputDef() string {
	if x != nil {
		return x.InputDef
	}
	return ""
}

func (x *ProvidedCapability) GetStepContract() *StepContract {
	if x != nil {
		return x.StepContract
	}
	return nil
}

func (x *ProvidedCapability) GetStructural() bool {
	if x != nil {
		return x.Structural
	}
	return false
}

func (x *ProvidedCapability) GetLifecycle() bool {
	if x != nil {
		return x.Lifecycle
	}
	return false
}

func (x *ProvidedCapability) GetPreresolve() bool {
	if x != nil {
		return x.Preresolve
	}
	return false
}

func (x *ProvidedCapability) GetValidates() bool {
	if x != nil {
		return x.Validates
	}
	return false
}

func (x *ProvidedCapability) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProvidedCapability) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *ProvidedCapability) GetDeployTraits() *DeployTraits {
	if x != nil {
		return x.DeployTraits
	}
	return nil
}

func (x *ProvidedCapability) GetSubcommands() []*CLISubcommand {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

func (x *ProvidedCapability) GetCommandModelJson() []byte {
	if x != nil {
		return x.CommandModelJson
	}
	return nil
}

// CLISubcommand — one DECLARED child of a class="command" capability's own CLI word (F-CLI-NEST).
// A plain name+help pair, not a full grammar: the host renders it as a Kong `cmd:""` child whose
// OWN body is still a pass-through Args leaf (the plugin's real internal flag/positional shape
// stays invisible to the host, exactly like today's flat holder — only the NAMING becomes real).
// A hidden child (hidden=true) is HIDDEN-BUT-REACHABLE: still a real Kong `cmd:""` node tagged
// `hidden:""` (so it DISPATCHES — e.g. the iterate harness's `charly check run-local` re-exec —
// but stays out of `--help` and the CLI model/MCP tool surface).
type CLISubcommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the subcommand word, e.g. "live", "boxes"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// one-line help text, shown in `--help` and used as the MCP tool description
	Help string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	// hidden-but-reachable: the host renders a hidden child with a Kong `hidden:""` tag — it is still a REAL dispatchable cmd node, but `--help` and the CLI model (MCP) keep it invisible, mirroring the `hidden:""` tag on the plugin's own grammar struct field (KongSubcommands derives it)
	Hidden        bool `protobuf:"varint,3,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLISubcommand) Reset() {
	*x = CLISubcommand{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLISubcommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLISubcommand) ProtoMessage() {}

func (x *CLISubcommand) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLISubcommand.ProtoReflect.Descriptor instead.
func (*CLISubcommand) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CLISubcommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CLISubcommand) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *CLISubcommand) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// DeployTraits — a SUBSTRATE kind's DECLARED deploy behaviour (P9), advertised per substrate
// word over Describe and stamped by kit.StampDescent onto the node's DescentDescriptor. This is
// the SINGLE plugin-declared source for "how does this substrate behave in the deploy chain",
// so the kernel consults it BY TRAIT (off node.Descent) — never by switching on the kind word.
// Canonical table: pod=container+image_backed+image_context; vm=ssh+machine_venue+exclusive_venue;
// local=shell+machine_venue; kubernetes=shell+image_context+leaf_only; android=parent; zero value =
// external-in-place. Empty/absent for every non-kind (or non-substrate kind) capability.
type DeployTraits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "container" | "ssh" | "shell" | "parent" | "none": how commands physically execute in this substrate's venue
	Venue string `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	// the substrate runs a baked OCI image (pod)
	ImageBacked bool `protobuf:"varint,2,opt,name=image_backed,json=imageBacked,proto3" json:"image_backed,omitempty"`
	// the substrate composes over an image build context (pod overlay, kubernetes manifests)
	ImageContext bool `protobuf:"varint,3,opt,name=image_context,json=imageContext,proto3" json:"image_context,omitempty"`
	// the substrate is a full machine with a system init (host/vm/local) — services render as systemd units, not a container init
	MachineVenue bool `protobuf:"varint,4,opt,name=machine_venue,json=machineVenue,proto3" json:"machine_venue,omitempty"`
	// the substrate holds an exclusive host-resource lease boundary (vm)
	ExclusiveVenue bool `protobuf:"varint,5,opt,name=exclusive_venue,json=exclusiveVenue,proto3" json:"exclusive_venue,omitempty"`
	// the substrate is a deploy-chain LEAF — it cannot be descended into (kubernetes)
	LeafOnly bool `protobuf:"varint,6,opt,name=leaf_only,json=leafOnly,proto3" json:"leaf_only,omitempty"`
	// the substrate's Start/Stop accept direct-mode CLI opts AND need the Q1 resource-arbiter claim bracketed around the dispatch (pod); a substrate that manages its own venue lifecycle + resource claim (vm) leaves this false
	BracketedLifecycle bool `protobuf:"varint,7,opt,name=bracketed_lifecycle,json=bracketedLifecycle,proto3" json:"bracketed_lifecycle,omitempty"`
	// the substrate is a valid kind:check bed target (pod/vm/local/android); kubernetes and unknown words are not
	BedTarget bool `protobuf:"varint,8,opt,name=bed_target,json=bedTarget,proto3" json:"bed_target,omitempty"`
	// the substrate's Add/Del path wires the ephemeral register/teardown seam (TTL timer + charly.yml persistence) — vm only today
	SupportsEphemeral bool `protobuf:"varint,9,opt,name=supports_ephemeral,json=supportsEphemeral,proto3" json:"supports_ephemeral,omitempty"`
	// the substrate has a backing chain from_snapshot restores from — vm only
	SupportsFromSnapshot bool `protobuf:"varint,10,opt,name=supports_from_snapshot,json=supportsFromSnapshot,proto3" json:"supports_from_snapshot,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeployTraits) Reset() {
	*x = DeployTraits{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployTraits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployTraits) ProtoMessage() {}

func (x *DeployTraits) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployTraits.ProtoReflect.Descriptor instead.
func (*DeployTraits) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DeployTraits) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *DeployTraits) GetImageBacked() bool {
	if x != nil {
		return x.ImageBacked
	}
	return false
}

func (x *DeployTraits) GetImageContext() bool {
	if x != nil {
		return x.ImageContext
	}
	return false
}

func (x *DeployTraits) GetMachineVenue() bool {
	if x != nil {
		return x.MachineVenue
	}
	return false
}

func (x *DeployTraits) GetExclusiveVenue() bool {
	if x != nil {
		return x.ExclusiveVenue
	}
	return false
}

func (x *DeployTraits) GetLeafOnly() bool {
	if x != nil {
		return x.LeafOnly
	}
	return false
}

func (x *DeployTraits) GetBracketedLifecycle() bool {
	if x != nil {
		return x.BracketedLifecycle
	}
	return false
}

func (x *DeployTraits) GetBedTarget() bool {
	if x != nil {
		return x.BedTarget
	}
	return false
}

func (x *DeployTraits) GetSupportsEphemeral() bool {
	if x != nil {
		return x.SupportsEphemeral
	}
	return false
}

func (x *DeployTraits) GetSupportsFromSnapshot() bool {
	if x != nil {
		return x.SupportsFromSnapshot
	}
	return false
}

// StepContract — a class="step" plugin's DECLARED install-step contract (F3): where the
// step's effect lands (scope) + where its commands execute (venue) + the opt-in gate it
// needs. This is what makes an external step kind a first-class IR step whose privilege /
// gating the host applies WITHOUT a compiled-in case (the open default arm). Reverse is NOT
// declared — an external step's teardown ops are DYNAMIC, recorded from its OpExecute reply
// (the same record-and-replay as ExternalPluginStep). Empty/absent for non-step capabilities.
type StepContract struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "system" | "user" | "user-profile"
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Venue enum: 0=host-native, 1=container-builder, 2=skip
	Venue int32 `protobuf:"varint,2,opt,name=venue,proto3" json:"venue,omitempty"`
	// "" | "allow-repo-changes" | "allow-root-tasks" | "with-services"
	Gate string `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	// F-STEP-EMIT: the step produces a build-context Containerfile FRAGMENT (Invoke(OpEmit)); the pod-overlay OCITarget bakes it. false => deploy-only step (no build fragment; OCITarget skips it, like apk on an image build)
	Emits         bool `protobuf:"varint,4,opt,name=emits,proto3" json:"emits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepContract) Reset() {
	*x = StepContract{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepContract) ProtoMessage() {}

func (x *StepContract) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepContract.ProtoReflect.Descriptor instead.
func (*StepContract) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *StepContract) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StepContract) GetVenue() int32 {
	if x != nil {
		return x.Venue
	}
	return 0
}

func (x *StepContract) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *StepContract) GetEmits() bool {
	if x != nil {
		return x.Emits
	}
	return false
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the reserved word, e.g. "exampleprobe","cdp","local"
	Reserved string `protobuf:"bytes,1,opt,name=reserved,proto3" json:"reserved,omitempty"`
	// operation selector for the word's class
	Op string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	// the CUE-generated params (Op for verbs/steps; entity for kinds)
	ParamsJson []byte `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	// snapshotCheckEnv / venue descriptor (serializable invocation ctx)
	EnvJson []byte `protobuf:"bytes,4,opt,name=env_json,json=envJson,proto3" json:"env_json,omitempty"`
	// the ProviderClass ("verb"/"kind"/...) — words aren't unique across classes
	Class string `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	// E3b: the go-plugin broker id the host serves ExecutorService on for a deploy/step/builder op; 0 = none (verb/kind ops need no executor)
	ExecutorBrokerId uint32 `protobuf:"varint,6,opt,name=executor_broker_id,json=executorBrokerId,proto3" json:"executor_broker_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeRequest) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

func (x *InvokeRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *InvokeRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *InvokeRequest) GetEnvJson() []byte {
	if x != nil {
		return x.EnvJson
	}
	return nil
}

func (x *InvokeRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *InvokeRequest) GetExecutorBrokerId() uint32 {
	if x != nil {
		return x.ExecutorBrokerId
	}
	return 0
}

// CheckResult / InstallPlan / Diagnostics, JSON
type InvokeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeReply) Reset() {
	*x = InvokeReply{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeReply) ProtoMessage() {}

func (x *InvokeReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeReply.ProtoReflect.Descriptor instead.
func (*InvokeReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeReply) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

// one streamed result frame (single-shot sends one)
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Frame) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

// ChannelFrame is the generic, bidirectional provider process channel. Domain payloads remain CUE-generated JSON; this envelope owns ordering, flow control, terminal data, and lifecycle signals without naming a runtime or transport.
type ChannelFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stable idempotency/correlation key for the channel
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// monotonic sender sequence; zero is reserved for an unsequenced open
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// highest contiguous peer sequence consumed
	AckSequence uint64 `protobuf:"varint,3,opt,name=ack_sequence,json=ackSequence,proto3" json:"ack_sequence,omitempty"`
	// open|stdin|stdout|stderr|terminal|status|resize|signal|ack|cancel|exit|error|resync
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// provider class, set on open
	Class string `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	// provider word, set on open
	Reserved string `protobuf:"bytes,6,opt,name=reserved,proto3" json:"reserved,omitempty"`
	// provider operation, set on open
	Op string `protobuf:"bytes,7,opt,name=op,proto3" json:"op,omitempty"`
	// CUE-generated domain payload or structured status
	PayloadJson []byte `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// binary-safe process or terminal bytes; never shell-interpreted
	Data []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// canonical key, signal, stream, or status name
	Name     string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Cols     uint32 `protobuf:"varint,11,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows     uint32 `protobuf:"varint,12,opt,name=rows,proto3" json:"rows,omitempty"`
	ExitCode int32  `protobuf:"varint,13,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error    string `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	// CUE-generated generic target chain, set on open
	TargetJson []byte `protobuf:"bytes,15,opt,name=target_json,json=targetJson,proto3" json:"target_json,omitempty"`
	// first sequence requested during attach/resynchronization
	ReplayFrom    uint64 `protobuf:"varint,16,opt,name=replay_from,json=replayFrom,proto3" json:"replay_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelFrame) Reset() {
	*x = ChannelFrame{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelFrame) ProtoMessage() {}

func (x *ChannelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelFrame.ProtoReflect.Descriptor instead.
func (*ChannelFrame) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChannelFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChannelFrame) GetAckSequence() uint64 {
	if x != nil {
		return x.AckSequence
	}
	return 0
}

func (x *ChannelFrame) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChannelFrame) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ChannelFrame) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

func (x *ChannelFrame) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ChannelFrame) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *ChannelFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChannelFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelFrame) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ChannelFrame) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ChannelFrame) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ChannelFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChannelFrame) GetTargetJson() []byte {
	if x != nil {
		return x.TargetJson
	}
	return nil
}

func (x *ChannelFrame) GetReplayFrom() uint64 {
	if x != nil {
		return x.ReplayFrom
	}
	return 0
}

// InvokeProviderRequest mirrors InvokeRequest minus the broker id (the host already holds the
// reverse context): dispatch op `op` on provider (class, reserved) with params/env (F10).
type InvokeProviderRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Class      string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Reserved   string                 `protobuf:"bytes,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Op         string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	ParamsJson []byte                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	EnvJson    []byte                 `protobuf:"bytes,5,opt,name=env_json,json=envJson,proto3" json:"env_json,omitempty"`
	// OPTIONAL marshalled spec.VenueDescriptor (S1 — the venue-scoped-executor-session
	// seam). The calling plugin supplies its OWN self-described venue (shell or ssh) when
	// it wants the target provider Invoked WITH a live executor but holds no enclosing
	// executor of its own to forward (e.g. a verb/kind Invoke with no deploy-context
	// broker). On presence, the host re-materializes a FRESH DeployExecutor from the
	// descriptor (venueFromDescriptor) and threads THAT onto the nested InvokeWithExecutor
	// call instead of the caller's own executor. Empty/absent — byte-identical prior
	// behavior (the caller's own executor, if any, is forwarded as before).
	VenueDescriptorJson []byte `protobuf:"bytes,6,opt,name=venue_descriptor_json,json=venueDescriptorJson,proto3" json:"venue_descriptor_json,omitempty"`
	// OPTIONAL canonical candy ref (S3b — the Pass-2 lazy-connect gap). The host's
	// InvokeProvider handler falls back to connectPluginByWordRef(class, word, extraRef)
	// on a registry miss (S2); passing "" only ever reaches Pass-1 (the calling project's
	// own candy closure) — a target declared nowhere in that closure but resolvable via an
	// explicit @github canonical ref (the same Pass-2 fetch the credential/vm/kube host
	// adapters already use) needs this field set. Empty/absent — byte-identical S2
	// behavior (Pass-1 only).
	ExtraRef      string `protobuf:"bytes,7,opt,name=extra_ref,json=extraRef,proto3" json:"extra_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeProviderRequest) Reset() {
	*x = InvokeProviderRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProviderRequest) ProtoMessage() {}

func (x *InvokeProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProviderRequest.ProtoReflect.Descriptor instead.
func (*InvokeProviderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *InvokeProviderRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *InvokeProviderRequest) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

func (x *InvokeProviderRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *InvokeProviderRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *InvokeProviderRequest) GetEnvJson() []byte {
	if x != nil {
		return x.EnvJson
	}
	return nil
}

func (x *InvokeProviderRequest) GetVenueDescriptorJson() []byte {
	if x != nil {
		return x.VenueDescriptorJson
	}
	return nil
}

func (x *InvokeProviderRequest) GetExtraRef() string {
	if x != nil {
		return x.ExtraRef
	}
	return ""
}

// HostBuildRequest names a registered host-builder `kind` (e.g. "plugin-binary", and — added by
// M13/M14 — "kustomize"/"image") + an opaque `spec_json` it interprets (F10). HostBuildReply
// carries the builder's opaque result (e.g. an artifact path/handle JSON) or an error.
type HostBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	SpecJson      []byte                 `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostBuildRequest) Reset() {
	*x = HostBuildRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBuildRequest) ProtoMessage() {}

func (x *HostBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBuildRequest.ProtoReflect.Descriptor instead.
func (*HostBuildRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *HostBuildRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HostBuildRequest) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

// DescribeProviderRequest (K5-A item 2): ask the host for the CACHED capability
// metadata of another provider by (class, word) — no live Describe round-trip, no
// Invoke. This is what a plugin needs to make a routing DECISION about a peer
// provider (e.g. "does class:step word X declare Emits=true?") without holding its
// own copy of the provider registry — the same registry-consult gap InvokeProvider
// solves for DISPATCH, DescribeProvider solves for METADATA. class/word are DATA (the
// F11 uniform-API invariant): the RPC itself never names a plugin word.
type DescribeProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeProviderRequest) Reset() {
	*x = DescribeProviderRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeProviderRequest) ProtoMessage() {}

func (x *DescribeProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeProviderRequest.ProtoReflect.Descriptor instead.
func (*DescribeProviderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeProviderRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *DescribeProviderRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// found=false means (class, word) resolves to no CONNECTED provider (mirrors
// InvokeProvider's own "provider not connected" failure mode, but as a query result
// rather than an RPC error — a plugin routing decision often wants to distinguish
// "not found" from a transport failure). step_contract is populated only when the
// resolved provider is class="step" AND declares one (F3) — absent/nil for every
// other class, exactly like ProvidedCapability.step_contract's own optionality. Kept
// narrowly scoped to StepContract (the ONE cached sub-shape a consumer needs today,
// oci_step_emit.go's relocation) rather than the whole ProvidedCapability — extend
// with additional cached fields only when a consumer actually needs them.
type DescribeProviderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	StepContract  *StepContract          `protobuf:"bytes,2,opt,name=step_contract,json=stepContract,proto3" json:"step_contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeProviderReply) Reset() {
	*x = DescribeProviderReply{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeProviderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeProviderReply) ProtoMessage() {}

func (x *DescribeProviderReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeProviderReply.ProtoReflect.Descriptor instead.
func (*DescribeProviderReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *DescribeProviderReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DescribeProviderReply) GetStepContract() *StepContract {
	if x != nil {
		return x.StepContract
	}
	return nil
}

type HostBuildReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostBuildReply) Reset() {
	*x = HostBuildReply{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostBuildReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBuildReply) ProtoMessage() {}

func (x *HostBuildReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBuildReply.ProtoReflect.Descriptor instead.
func (*HostBuildReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *HostBuildReply) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *HostBuildReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VenueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venue         string                 `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueReply) Reset() {
	*x = VenueReply{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueReply) ProtoMessage() {}

func (x *VenueReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueReply.ProtoReflect.Descriptor instead.
func (*VenueReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *VenueReply) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

// opts_json = EmitOpts, JSON
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	OptsJson      []byte                 `protobuf:"bytes,2,opt,name=opts_json,json=optsJson,proto3" json:"opts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *RunRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *RunRequest) GetOptsJson() []byte {
	if x != nil {
		return x.OptsJson
	}
	return nil
}

// empty error = success
type RunReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunReply) Reset() {
	*x = RunReply{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunReply) ProtoMessage() {}

func (x *RunReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunReply.ProtoReflect.Descriptor instead.
func (*RunReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *RunReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// content placed at path; mode = octal perms; opts_json = EmitOpts
type PutFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	OwnerRoot     bool                   `protobuf:"varint,4,opt,name=owner_root,json=ownerRoot,proto3" json:"owner_root,omitempty"`
	OptsJson      []byte                 `protobuf:"bytes,5,opt,name=opts_json,json=optsJson,proto3" json:"opts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *PutFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PutFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PutFileRequest) GetOwnerRoot() bool {
	if x != nil {
		return x.OwnerRoot
	}
	return false
}

func (x *PutFileRequest) GetOptsJson() []byte {
	if x != nil {
		return x.OptsJson
	}
	return nil
}

// empty error = success
type PutFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileReply) Reset() {
	*x = PutFileReply{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileReply) ProtoMessage() {}

func (x *PutFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileReply.ProtoReflect.Descriptor instead.
func (*PutFileReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *PutFileReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// error = execution failure, NOT a non-zero exit
type CaptureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureReply) Reset() {
	*x = CaptureReply{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureReply) ProtoMessage() {}

func (x *CaptureReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureReply.ProtoReflect.Descriptor instead.
func (*CaptureReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *CaptureReply) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CaptureReply) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CaptureReply) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CaptureReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// F12 RunInteractive/RunStream: stdout/stderr/stdin went LIVE to the operator's terminal (host-held), so no buffers — only the session's exit code; error = execution/spawn failure, NOT a non-zero exit (CaptureReply's split, sans buffers)
type LiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveReply) Reset() {
	*x = LiveReply{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveReply) ProtoMessage() {}

func (x *LiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveReply.ProtoReflect.Descriptor instead.
func (*LiveReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *LiveReply) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *LiveReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	AsRoot        bool                   `protobuf:"varint,2,opt,name=as_root,json=asRoot,proto3" json:"as_root,omitempty"`
	OptsJson      []byte                 `protobuf:"bytes,3,opt,name=opts_json,json=optsJson,proto3" json:"opts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileRequest) GetAsRoot() bool {
	if x != nil {
		return x.AsRoot
	}
	return false
}

func (x *GetFileRequest) GetOptsJson() []byte {
	if x != nil {
		return x.OptsJson
	}
	return nil
}

type GetFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileReply) Reset() {
	*x = GetFileReply{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReply) ProtoMessage() {}

func (x *GetFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReply.ProtoReflect.Descriptor instead.
func (*GetFileReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *GetFileReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetFileReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// step_json = ONE spec.InstallStepView (a HOST-ENGINE step kind — Builder, LocalPkgInstall,
// SystemPackages, an act-verb Op, or ExternalPlugin — projected by stepToView); opts_json =
// EmitOpts. reverse_ops_json = the step's recorded []spec.ReverseOp (the plugin folds them
// into its DeployReply for record-and-replay teardown). error = a host-engine/apply FAILURE
// on the venue (the RPC itself succeeds — the failure rides the reply field, like
// RunReply/CaptureReply).
type HostStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepJson      []byte                 `protobuf:"bytes,1,opt,name=step_json,json=stepJson,proto3" json:"step_json,omitempty"`
	OptsJson      []byte                 `protobuf:"bytes,2,opt,name=opts_json,json=optsJson,proto3" json:"opts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStepRequest) Reset() {
	*x = HostStepRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStepRequest) ProtoMessage() {}

func (x *HostStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStepRequest.ProtoReflect.Descriptor instead.
func (*HostStepRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *HostStepRequest) GetStepJson() []byte {
	if x != nil {
		return x.StepJson
	}
	return nil
}

func (x *HostStepRequest) GetOptsJson() []byte {
	if x != nil {
		return x.OptsJson
	}
	return nil
}

type HostStepReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReverseOpsJson []byte                 `protobuf:"bytes,1,opt,name=reverse_ops_json,json=reverseOpsJson,proto3" json:"reverse_ops_json,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostStepReply) Reset() {
	*x = HostStepReply{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStepReply) ProtoMessage() {}

func (x *HostStepReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStepReply.ProtoReflect.Descriptor instead.
func (*HostStepReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *HostStepReply) GetReverseOpsJson() []byte {
	if x != nil {
		return x.ReverseOpsJson
	}
	return nil
}

func (x *HostStepReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HTTPDoRequest carries the FULL request + per-request policy the host needs to build the
// client (httpClientFor) host-side: ca_pem is the resolved CA PEM bytes (the candy reads its
// authored ca_file host-side and ships the bytes), timeout is a Go duration string ("" = base).
type HTTPDoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Method            string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url               string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body              []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers           map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout           string                 `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	AllowInsecure     bool                   `protobuf:"varint,6,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	NoFollowRedirects bool                   `protobuf:"varint,7,opt,name=no_follow_redirects,json=noFollowRedirects,proto3" json:"no_follow_redirects,omitempty"`
	CaPem             []byte                 `protobuf:"bytes,8,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HTTPDoRequest) Reset() {
	*x = HTTPDoRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPDoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDoRequest) ProtoMessage() {}

func (x *HTTPDoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDoRequest.ProtoReflect.Descriptor instead.
func (*HTTPDoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *HTTPDoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPDoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPDoRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPDoRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPDoRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HTTPDoRequest) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *HTTPDoRequest) GetNoFollowRedirects() bool {
	if x != nil {
		return x.NoFollowRedirects
	}
	return false
}

func (x *HTTPDoRequest) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

// HTTPDoReply: status + body + response headers, or a transport-level error (the RPC itself
// succeeds — a failed request rides the error field, like RunReply/CaptureReply).
type HTTPDoReply struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body   []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// pre-formatted "Key: value\n" blob (multi-value preserved), matcher-ready
	HeaderBlob    string `protobuf:"bytes,3,opt,name=header_blob,json=headerBlob,proto3" json:"header_blob,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPDoReply) Reset() {
	*x = HTTPDoReply{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPDoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDoReply) ProtoMessage() {}

func (x *HTTPDoReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDoReply.ProtoReflect.Descriptor instead.
func (*HTTPDoReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *HTTPDoReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPDoReply) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPDoReply) GetHeaderBlob() string {
	if x != nil {
		return x.HeaderBlob
	}
	return ""
}

func (x *HTTPDoReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddBackgroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBackgroundRequest) Reset() {
	*x = AddBackgroundRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBackgroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackgroundRequest) ProtoMessage() {}

func (x *AddBackgroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackgroundRequest.ProtoReflect.Descriptor instead.
func (*AddBackgroundRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *AddBackgroundRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ResolveEndpointRequest: the in-venue TCP port to resolve to a host-reachable address.
type ResolveEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEndpointRequest) Reset() {
	*x = ResolveEndpointRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointRequest) ProtoMessage() {}

func (x *ResolveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *ResolveEndpointRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ResolveEndpointReply: the host-reachable "host:port" addr, or a resolution error.
type ResolveEndpointReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEndpointReply) Reset() {
	*x = ResolveEndpointReply{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointReply) ProtoMessage() {}

func (x *ResolveEndpointReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointReply.ProtoReflect.Descriptor instead.
func (*ResolveEndpointReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *ResolveEndpointReply) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ResolveEndpointReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ResolveGraphicsEndpointRequest: the graphics kind to resolve ("vnc" | "spice").
type ResolveGraphicsEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGraphicsEndpointRequest) Reset() {
	*x = ResolveGraphicsEndpointRequest{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGraphicsEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGraphicsEndpointRequest) ProtoMessage() {}

func (x *ResolveGraphicsEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGraphicsEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveGraphicsEndpointRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveGraphicsEndpointRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// ResolveGraphicsEndpointReply: the dialable endpoint. Exactly one of addr / socket is set;
// password is the resolved ticket (empty = no auth). skip=true with skip_message signals a
// deployment with no graphics device of that kind (an N/A skip, not a failure).
type ResolveGraphicsEndpointReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Socket        string                 `protobuf:"bytes,2,opt,name=socket,proto3" json:"socket,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Skip          bool                   `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	SkipMessage   string                 `protobuf:"bytes,5,opt,name=skip_message,json=skipMessage,proto3" json:"skip_message,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGraphicsEndpointReply) Reset() {
	*x = ResolveGraphicsEndpointReply{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGraphicsEndpointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGraphicsEndpointReply) ProtoMessage() {}

func (x *ResolveGraphicsEndpointReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGraphicsEndpointReply.ProtoReflect.Descriptor instead.
func (*ResolveGraphicsEndpointReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *ResolveGraphicsEndpointReply) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ResolveGraphicsEndpointReply) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *ResolveGraphicsEndpointReply) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResolveGraphicsEndpointReply) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ResolveGraphicsEndpointReply) GetSkipMessage() string {
	if x != nil {
		return x.SkipMessage
	}
	return ""
}

func (x *ResolveGraphicsEndpointReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ResolveImageLabelRequest: the OCI label name to read (e.g. "ai.opencharly.mcp_provide").
type ResolveImageLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveImageLabelRequest) Reset() {
	*x = ResolveImageLabelRequest{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveImageLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveImageLabelRequest) ProtoMessage() {}

func (x *ResolveImageLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveImageLabelRequest.ProtoReflect.Descriptor instead.
func (*ResolveImageLabelRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *ResolveImageLabelRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// ResolveImageLabelReply: the raw label value ("" = label absent on the image).
type ResolveImageLabelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveImageLabelReply) Reset() {
	*x = ResolveImageLabelReply{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveImageLabelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveImageLabelReply) ProtoMessage() {}

func (x *ResolveImageLabelReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveImageLabelReply.ProtoReflect.Descriptor instead.
func (*ResolveImageLabelReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *ResolveImageLabelReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResolveImageLabelReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\fcharlyplugin\"\a\n" +
	"\x05Empty\"\xae\x01\n" +
	"\fCapabilities\x12\x16\n" +
	"\x06calver\x18\x01 \x01(\tR\x06calver\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12<\n" +
	"\bprovided\x18\x03 \x03(\v2 .charlyplugin.ProvidedCapabilityR\bprovided\x12\x1d\n" +
	"\n" +
	"schema_cue\x18\x04 \x01(\tR\tschemaCue\"\xf6\x03\n" +
	"\x12ProvidedCapability\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1b\n" +
	"\tinput_def\x18\x03 \x01(\tR\binputDef\x12?\n" +
	"\rstep_contract\x18\x04 \x01(\v2\x1a.charlyplugin.StepContractR\fstepContract\x12\x1e\n" +
	"\n" +
	"structural\x18\x05 \x01(\bR\n" +
	"structural\x12\x1c\n" +
	"\tlifecycle\x18\x06 \x01(\bR\tlifecycle\x12\x1e\n" +
	"\n" +
	"preresolve\x18\a \x01(\bR\n" +
	"preresolve\x12\x1c\n" +
	"\tvalidates\x18\b \x01(\bR\tvalidates\x12\x14\n" +
	"\x05phase\x18\t \x01(\tR\x05phase\x12\x18\n" +
	"\aprimary\x18\n" +
	" \x01(\tR\aprimary\x12?\n" +
	"\rdeploy_traits\x18\v \x01(\v2\x1a.charlyplugin.DeployTraitsR\fdeployTraits\x12=\n" +
	"\vsubcommands\x18\f \x03(\v2\x1b.charlyplugin.CLISubcommandR\vsubcommands\x12,\n" +
	"\x12command_model_json\x18\r \x01(\fR\x10commandModelJson\"O\n" +
	"\rCLISubcommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04help\x18\x02 \x01(\tR\x04help\x12\x16\n" +
	"\x06hidden\x18\x03 \x01(\bR\x06hidden\"\x8c\x03\n" +
	"\fDeployTraits\x12\x14\n" +
	"\x05venue\x18\x01 \x01(\tR\x05venue\x12!\n" +
	"\fimage_backed\x18\x02 \x01(\bR\vimageBacked\x12#\n" +
	"\rimage_context\x18\x03 \x01(\bR\fimageContext\x12#\n" +
	"\rmachine_venue\x18\x04 \x01(\bR\fmachineVenue\x12'\n" +
	"\x0fexclusive_venue\x18\x05 \x01(\bR\x0eexclusiveVenue\x12\x1b\n" +
	"\tleaf_only\x18\x06 \x01(\bR\bleafOnly\x12/\n" +
	"\x13bracketed_lifecycle\x18\a \x01(\bR\x12bracketedLifecycle\x12\x1d\n" +
	"\n" +
	"bed_target\x18\b \x01(\bR\tbedTarget\x12-\n" +
	"\x12supports_ephemeral\x18\t \x01(\bR\x11supportsEphemeral\x124\n" +
	"\x16supports_from_snapshot\x18\n" +
	" \x01(\bR\x14supportsFromSnapshot\"d\n" +
	"\fStepContract\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05venue\x18\x02 \x01(\x05R\x05venue\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x14\n" +
	"\x05emits\x18\x04 \x01(\bR\x05emits\"\xbb\x01\n" +
	"\rInvokeRequest\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\tR\breserved\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\fR\n" +
	"paramsJson\x12\x19\n" +
	"\benv_json\x18\x04 \x01(\fR\aenvJson\x12\x14\n" +
	"\x05class\x18\x05 \x01(\tR\x05class\x12,\n" +
	"\x12executor_broker_id\x18\x06 \x01(\rR\x10executorBrokerId\".\n" +
	"\vInvokeReply\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"(\n" +
	"\x05Frame\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"\xaa\x03\n" +
	"\fChannelFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\fack_sequence\x18\x03 \x01(\x04R\vackSequence\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05class\x18\x05 \x01(\tR\x05class\x12\x1a\n" +
	"\breserved\x18\x06 \x01(\tR\breserved\x12\x0e\n" +
	"\x02op\x18\a \x01(\tR\x02op\x12!\n" +
	"\fpayload_json\x18\b \x01(\fR\vpayloadJson\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04cols\x18\v \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\f \x01(\rR\x04rows\x12\x1b\n" +
	"\texit_code\x18\r \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12\x1f\n" +
	"\vtarget_json\x18\x0f \x01(\fR\n" +
	"targetJson\x12\x1f\n" +
	"\vreplay_from\x18\x10 \x01(\x04R\n" +
	"replayFrom\"\xe6\x01\n" +
	"\x15InvokeProviderRequest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\tR\breserved\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\fR\n" +
	"paramsJson\x12\x19\n" +
	"\benv_json\x18\x05 \x01(\fR\aenvJson\x122\n" +
	"\x15venue_descriptor_json\x18\x06 \x01(\fR\x13venueDescriptorJson\x12\x1b\n" +
	"\textra_ref\x18\a \x01(\tR\bextraRef\"C\n" +
	"\x10HostBuildRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\fR\bspecJson\"C\n" +
	"\x17DescribeProviderRequest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\"n\n" +
	"\x15DescribeProviderReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12?\n" +
	"\rstep_contract\x18\x02 \x01(\v2\x1a.charlyplugin.StepContractR\fstepContract\"G\n" +
	"\x0eHostBuildReply\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\"\n" +
	"\n" +
	"VenueReply\x12\x14\n" +
	"\x05venue\x18\x01 \x01(\tR\x05venue\"A\n" +
	"\n" +
	"RunRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1b\n" +
	"\topts_json\x18\x02 \x01(\fR\boptsJson\" \n" +
	"\bRunReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x8e\x01\n" +
	"\x0ePutFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"owner_root\x18\x04 \x01(\bR\townerRoot\x12\x1b\n" +
	"\topts_json\x18\x05 \x01(\fR\boptsJson\"$\n" +
	"\fPutFileReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"q\n" +
	"\fCaptureReply\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\">\n" +
	"\tLiveReply\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Z\n" +
	"\x0eGetFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\aas_root\x18\x02 \x01(\bR\x06asRoot\x12\x1b\n" +
	"\topts_json\x18\x03 \x01(\fR\boptsJson\">\n" +
	"\fGetFileReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x0fHostStepRequest\x12\x1b\n" +
	"\tstep_json\x18\x01 \x01(\fR\bstepJson\x12\x1b\n" +
	"\topts_json\x18\x02 \x01(\fR\boptsJson\"O\n" +
	"\rHostStepReply\x12(\n" +
	"\x10reverse_ops_json\x18\x01 \x01(\fR\x0ereverseOpsJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd5\x02\n" +
	"\rHTTPDoRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12B\n" +
	"\aheaders\x18\x04 \x03(\v2(.charlyplugin.HTTPDoRequest.HeadersEntryR\aheaders\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\tR\atimeout\x12%\n" +
	"\x0eallow_insecure\x18\x06 \x01(\bR\rallowInsecure\x12.\n" +
	"\x13no_follow_redirects\x18\a \x01(\bR\x11noFollowRedirects\x12\x15\n" +
	"\x06ca_pem\x18\b \x01(\fR\x05caPem\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\vHTTPDoReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1f\n" +
	"\vheader_blob\x18\x03 \x01(\tR\n" +
	"headerBlob\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"(\n" +
	"\x14AddBackgroundRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\",\n" +
	"\x16ResolveEndpointRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\"@\n" +
	"\x14ResolveEndpointReply\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x1eResolveGraphicsEndpointRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\xb3\x01\n" +
	"\x1cResolveGraphicsEndpointReply\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x16\n" +
	"\x06socket\x18\x02 \x01(\tR\x06socket\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\bR\x04skip\x12!\n" +
	"\fskip_message\x18\x05 \x01(\tR\vskipMessage\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"0\n" +
	"\x18ResolveImageLabelRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"D\n" +
	"\x16ResolveImageLabelReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2I\n" +
	"\n" +
	"PluginMeta\x12;\n" +
	"\bDescribe\x12\x13.charlyplugin.Empty\x1a\x1a.charlyplugin.Capabilities2\xd7\x01\n" +
	"\bProvider\x12@\n" +
	"\x06Invoke\x12\x1b.charlyplugin.InvokeRequest\x1a\x19.charlyplugin.InvokeReply\x12B\n" +
	"\fInvokeStream\x12\x1b.charlyplugin.InvokeRequest\x1a\x13.charlyplugin.Frame0\x01\x12E\n" +
	"\aChannel\x12\x1a.charlyplugin.ChannelFrame\x1a\x1a.charlyplugin.ChannelFrame(\x010\x012\xe0\x06\n" +
	"\x0fExecutorService\x126\n" +
	"\x05Venue\x12\x13.charlyplugin.Empty\x1a\x18.charlyplugin.VenueReply\x12=\n" +
	"\tRunSystem\x12\x18.charlyplugin.RunRequest\x1a\x16.charlyplugin.RunReply\x12;\n" +
	"\aRunUser\x12\x18.charlyplugin.RunRequest\x1a\x16.charlyplugin.RunReply\x12C\n" +
	"\aPutFile\x12\x1c.charlyplugin.PutFileRequest\x1a\x1a.charlyplugin.PutFileReply\x12B\n" +
	"\n" +
	"RunCapture\x12\x18.charlyplugin.RunRequest\x1a\x1a.charlyplugin.CaptureReply\x12C\n" +
	"\x0eRunInteractive\x12\x18.charlyplugin.RunRequest\x1a\x17.charlyplugin.LiveReply\x12>\n" +
	"\tRunStream\x12\x18.charlyplugin.RunRequest\x1a\x17.charlyplugin.LiveReply\x12C\n" +
	"\aGetFile\x12\x1c.charlyplugin.GetFileRequest\x1a\x1a.charlyplugin.GetFileReply\x12I\n" +
	"\vRunHostStep\x12\x1d.charlyplugin.HostStepRequest\x1a\x1b.charlyplugin.HostStepReply\x12P\n" +
	"\x0eInvokeProvider\x12#.charlyplugin.InvokeProviderRequest\x1a\x19.charlyplugin.InvokeReply\x12I\n" +
	"\tHostBuild\x12\x1e.charlyplugin.HostBuildRequest\x1a\x1c.charlyplugin.HostBuildReply\x12^\n" +
	"\x10DescribeProvider\x12%.charlyplugin.DescribeProviderRequest\x1a#.charlyplugin.DescribeProviderReply2\xd6\x03\n" +
	"\x13CheckContextService\x12@\n" +
	"\x06HTTPDo\x12\x1b.charlyplugin.HTTPDoRequest\x1a\x19.charlyplugin.HTTPDoReply\x12H\n" +
	"\rAddBackground\x12\".charlyplugin.AddBackgroundRequest\x1a\x13.charlyplugin.Empty\x12[\n" +
	"\x0fResolveEndpoint\x12$.charlyplugin.ResolveEndpointRequest\x1a\".charlyplugin.ResolveEndpointReply\x12s\n" +
	"\x17ResolveGraphicsEndpoint\x12,.charlyplugin.ResolveGraphicsEndpointRequest\x1a*.charlyplugin.ResolveGraphicsEndpointReply\x12a\n" +
	"\x11ResolveImageLabel\x12&.charlyplugin.ResolveImageLabelRequest\x1a$.charlyplugin.ResolveImageLabelReplyB\"Z github.com/opencharly/spec/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),                          // 0: charlyplugin.Empty
	(*Capabilities)(nil),                   // 1: charlyplugin.Capabilities
	(*ProvidedCapability)(nil),             // 2: charlyplugin.ProvidedCapability
	(*CLISubcommand)(nil),                  // 3: charlyplugin.CLISubcommand
	(*DeployTraits)(nil),                   // 4: charlyplugin.DeployTraits
	(*StepContract)(nil),                   // 5: charlyplugin.StepContract
	(*InvokeRequest)(nil),                  // 6: charlyplugin.InvokeRequest
	(*InvokeReply)(nil),                    // 7: charlyplugin.InvokeReply
	(*Frame)(nil),                          // 8: charlyplugin.Frame
	(*ChannelFrame)(nil),                   // 9: charlyplugin.ChannelFrame
	(*InvokeProviderRequest)(nil),          // 10: charlyplugin.InvokeProviderRequest
	(*HostBuildRequest)(nil),               // 11: charlyplugin.HostBuildRequest
	(*DescribeProviderRequest)(nil),        // 12: charlyplugin.DescribeProviderRequest
	(*DescribeProviderReply)(nil),          // 13: charlyplugin.DescribeProviderReply
	(*HostBuildReply)(nil),                 // 14: charlyplugin.HostBuildReply
	(*VenueReply)(nil),                     // 15: charlyplugin.VenueReply
	(*RunRequest)(nil),                     // 16: charlyplugin.RunRequest
	(*RunReply)(nil),                       // 17: charlyplugin.RunReply
	(*PutFileRequest)(nil),                 // 18: charlyplugin.PutFileRequest
	(*PutFileReply)(nil),                   // 19: charlyplugin.PutFileReply
	(*CaptureReply)(nil),                   // 20: charlyplugin.CaptureReply
	(*LiveReply)(nil),                      // 21: charlyplugin.LiveReply
	(*GetFileRequest)(nil),                 // 22: charlyplugin.GetFileRequest
	(*GetFileReply)(nil),                   // 23: charlyplugin.GetFileReply
	(*HostStepRequest)(nil),                // 24: charlyplugin.HostStepRequest
	(*HostStepReply)(nil),                  // 25: charlyplugin.HostStepReply
	(*HTTPDoRequest)(nil),                  // 26: charlyplugin.HTTPDoRequest
	(*HTTPDoReply)(nil),                    // 27: charlyplugin.HTTPDoReply
	(*AddBackgroundRequest)(nil),           // 28: charlyplugin.AddBackgroundRequest
	(*ResolveEndpointRequest)(nil),         // 29: charlyplugin.ResolveEndpointRequest
	(*ResolveEndpointReply)(nil),           // 30: charlyplugin.ResolveEndpointReply
	(*ResolveGraphicsEndpointRequest)(nil), // 31: charlyplugin.ResolveGraphicsEndpointRequest
	(*ResolveGraphicsEndpointReply)(nil),   // 32: charlyplugin.ResolveGraphicsEndpointReply
	(*ResolveImageLabelRequest)(nil),       // 33: charlyplugin.ResolveImageLabelRequest
	(*ResolveImageLabelReply)(nil),         // 34: charlyplugin.ResolveImageLabelReply
	nil,                                    // 35: charlyplugin.HTTPDoRequest.HeadersEntry
}
var file_plugin_proto_depIdxs = []int32{
	2,  // 0: charlyplugin.Capabilities.provided:type_name -> charlyplugin.ProvidedCapability
	5,  // 1: charlyplugin.ProvidedCapability.step_contract:type_name -> charlyplugin.StepContract
	4,  // 2: charlyplugin.ProvidedCapability.deploy_traits:type_name -> charlyplugin.DeployTraits
	3,  // 3: charlyplugin.ProvidedCapability.subcommands:type_name -> charlyplugin.CLISubcommand
	5,  // 4: charlyplugin.DescribeProviderReply.step_contract:type_name -> charlyplugin.StepContract
	35, // 5: charlyplugin.HTTPDoRequest.headers:type_name -> charlyplugin.HTTPDoRequest.HeadersEntry
	0,  // 6: charlyplugin.PluginMeta.Describe:input_type -> charlyplugin.Empty
	6,  // 7: charlyplugin.Provider.Invoke:input_type -> charlyplugin.InvokeRequest
	6,  // 8: charlyplugin.Provider.InvokeStream:input_type -> charlyplugin.InvokeRequest
	9,  // 9: charlyplugin.Provider.Channel:input_type -> charlyplugin.ChannelFrame
	0,  // 10: charlyplugin.ExecutorService.Venue:input_type -> charlyplugin.Empty
	16, // 11: charlyplugin.ExecutorService.RunSystem:input_type -> charlyplugin.RunRequest
	16, // 12: charlyplugin.ExecutorService.RunUser:input_type -> charlyplugin.RunRequest
	18, // 13: charlyplugin.ExecutorService.PutFile:input_type -> charlyplugin.PutFileRequest
	16, // 14: charlyplugin.ExecutorService.RunCapture:input_type -> charlyplugin.RunRequest
	16, // 15: charlyplugin.ExecutorService.RunInteractive:input_type -> charlyplugin.RunRequest
	16, // 16: charlyplugin.ExecutorService.RunStream:input_type -> charlyplugin.RunRequest
	22, // 17: charlyplugin.ExecutorService.GetFile:input_type -> charlyplugin.GetFileRequest
	24, // 18: charlyplugin.ExecutorService.RunHostStep:input_type -> charlyplugin.HostStepRequest
	10, // 19: charlyplugin.ExecutorService.InvokeProvider:input_type -> charlyplugin.InvokeProviderRequest
	11, // 20: charlyplugin.ExecutorService.HostBuild:input_type -> charlyplugin.HostBuildRequest
	12, // 21: charlyplugin.ExecutorService.DescribeProvider:input_type -> charlyplugin.DescribeProviderRequest
	26, // 22: charlyplugin.CheckContextService.HTTPDo:input_type -> charlyplugin.HTTPDoRequest
	28, // 23: charlyplugin.CheckContextService.AddBackground:input_type -> charlyplugin.AddBackgroundRequest
	29, // 24: charlyplugin.CheckContextService.ResolveEndpoint:input_type -> charlyplugin.ResolveEndpointRequest
	31, // 25: charlyplugin.CheckContextService.ResolveGraphicsEndpoint:input_type -> charlyplugin.ResolveGraphicsEndpointRequest
	33, // 26: charlyplugin.CheckContextService.ResolveImageLabel:input_type -> charlyplugin.ResolveImageLabelRequest
	1,  // 27: charlyplugin.PluginMeta.Describe:output_type -> charlyplugin.Capabilities
	7,  // 28: charlyplugin.Provider.Invoke:output_type -> charlyplugin.InvokeReply
	8,  // 29: charlyplugin.Provider.InvokeStream:output_type -> charlyplugin.Frame
	9,  // 30: charlyplugin.Provider.Channel:output_type -> charlyplugin.ChannelFrame
	15, // 31: charlyplugin.ExecutorService.Venue:output_type -> charlyplugin.VenueReply
	17, // 32: charlyplugin.ExecutorService.RunSystem:output_type -> charlyplugin.RunReply
	17, // 33: charlyplugin.ExecutorService.RunUser:output_type -> charlyplugin.RunReply
	19, // 34: charlyplugin.ExecutorService.PutFile:output_type -> charlyplugin.PutFileReply
	20, // 35: charlyplugin.ExecutorService.RunCapture:output_type -> charlyplugin.CaptureReply
	21, // 36: charlyplugin.ExecutorService.RunInteractive:output_type -> charlyplugin.LiveReply
	21, // 37: charlyplugin.ExecutorService.RunStream:output_type -> charlyplugin.LiveReply
	23, // 38: charlyplugin.ExecutorService.GetFile:output_type -> charlyplugin.GetFileReply
	25, // 39: charlyplugin.ExecutorService.RunHostStep:output_type -> charlyplugin.HostStepReply
	7,  // 40: charlyplugin.ExecutorService.InvokeProvider:output_type -> charlyplugin.InvokeReply
	14, // 41: charlyplugin.ExecutorService.HostBuild:output_type -> charlyplugin.HostBuildReply
	13, // 42: charlyplugin.ExecutorService.DescribeProvider:output_type -> charlyplugin.DescribeProviderReply
	27, // 43: charlyplugin.CheckContextService.HTTPDo:output_type -> charlyplugin.HTTPDoReply
	0,  // 44: charlyplugin.CheckContextService.AddBackground:output_type -> charlyplugin.Empty
	30, // 45: charlyplugin.CheckContextService.ResolveEndpoint:output_type -> charlyplugin.ResolveEndpointReply
	32, // 46: charlyplugin.CheckContextService.ResolveGraphicsEndpoint:output_type -> charlyplugin.ResolveGraphicsEndpointReply
	34, // 47: charlyplugin.CheckContextService.ResolveImageLabel:output_type -> charlyplugin.ResolveImageLabelReply
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
